import { ScheduledEvent } from "@cloudflare/workers-types";
import { ProviderManager, createProviderManager } from "./providers";
import { AIRequest, AgentConfig, ProviderName } from "./types";
import { ALL_MODELS } from "./models";
import {
  requireInternalAuth,
  checkInternalAuth,
  createInternalAuthMiddleware,
} from "@jango-blockchained/hoox-shared/middleware";
import {
  Errors,
  createJsonResponse,
  toError,
} from "@jango-blockchained/hoox-shared/errors";
import { healthCheck } from "@jango-blockchained/hoox-shared/health";
import { KVKeys } from "@jango-blockchained/hoox-shared/kvKeys";
import { createRouter } from "@jango-blockchained/hoox-shared/router";
import {
  createLogger,
  withRequestLog,
  corsHeaders,
} from "@jango-blockchained/hoox-shared/middleware";
import { serviceFetch } from "@jango-blockchained/hoox-shared/service-bindings";
import { createCronHandler } from "@jango-blockchained/hoox-shared/cron-handler";

import { fetchMarkPrice, sendCloseOrder } from "./logic/trade";
import { runHousekeeping } from "./logic/housekeeping";
import { processRoutine } from "./logic/routine";

// Re-export for backward compatibility with tests
export {
  requireInternalAuth,
  checkInternalAuth,
  processRoutine,
  fetchMarkPrice,
  sendCloseOrder,
};

const logger = createLogger({ service: "agent-worker" });

// Env is fully generated by wrangler types (worker-configuration.d.ts)
// All bindings (KV, AI, D1, Services) are inherited from Cloudflare.Env

function getProviderManager(env: Env): ProviderManager {
  return createProviderManager(env);
}

const router = createRouter<Env>();
const requireAuth = createInternalAuthMiddleware();

// --- Routes ---

router.post(
  "/agent/housekeeping",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    try {
      const results = await runHousekeeping(env, logger);
      return createJsonResponse(results, 200);
    } catch (error: unknown) {
      return Errors.internal(error);
    }
  },
  [requireAuth]
);

router.post(
  "/agent/risk-override",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    const body = (await request.json()) as { trailingStopPercent?: number };
    if (body.trailingStopPercent !== undefined) {
      await env.CONFIG_KV.put(
        KVKeys.KV_TRADE_TRAILING_STOP_PERCENT,
        body.trailingStopPercent.toString()
      );
    }
    return createJsonResponse({
      success: true,
      message: "Risk override applied",
    });
  },
  [requireAuth]
);

router.get(
  "/agent/status",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    const pm = getProviderManager(env);
    const config = await pm.loadConfig();
    return createJsonResponse({
      success: true,
      status: "Healthy",
      config: {
        defaultProvider: config.defaultProvider,
        fallbackChain: config.fallbackChain,
        modelMap: config.modelMap,
      },
      activeTrailingStops: await getActiveTrailingStops(env),
    });
  },
  [requireAuth]
);

router.get(
  "/agent/config",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    const pm = getProviderManager(env);
    const config = await pm.loadConfig();
    return createJsonResponse({
      success: true,
      config,
    });
  },
  [requireAuth]
);

router.post(
  "/agent/config",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    const body = (await request.json()) as Partial<AgentConfig>;
    const pm = getProviderManager(env);
    const updated = await pm.updateConfig(body);
    return createJsonResponse({ success: true, config: updated });
  },
  [requireAuth]
);

router.post(
  "/agent/test-model",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    const body = (await request.json()) as {
      provider?: ProviderName;
      model?: string;
      prompt?: string;
    };
    const pm = getProviderManager(env);
    const provider = body.provider || "workers-ai";
    const model = body.model;

    const testRequest: AIRequest = {
      messages: [
        { role: "system", content: "You are a helpful assistant." },
        {
          role: "user",
          content: body.prompt || 'Say "Hello" if you can hear me.',
        },
      ],
      model,
    };

    const result = await pm.run(testRequest);
    return createJsonResponse(
      {
        success: result.success,
        provider: result.provider,
        model: result.model,
        response: result.data?.response,
        error: result.error,
        latencyMs: result.latencyMs,
      },
      result.success ? 200 : 502
    );
  },
  [requireAuth]
);

router.get(
  "/agent/health",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    const pm = getProviderManager(env);
    const status = await pm.getProviderStatus();
    return createJsonResponse({
      success: true,
      providers: status,
    });
  }
);

router.get(
  "/agent/models",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    return createJsonResponse({
      success: true,
      models: ALL_MODELS,
    });
  },
  [requireAuth]
);

router.post(
  "/agent/chat",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    const body = (await request.json()) as {
      messages?: AIRequest["messages"];
      systemPrompt?: string;
      prompt?: string;
      temperature?: number;
      maxTokens?: number;
    };
    const pm = getProviderManager(env);
    const testRequest: AIRequest = {
      messages: body.messages || [
        {
          role: "system",
          content: body.systemPrompt || "You are a helpful trading assistant.",
        },
        { role: "user", content: body.prompt || "" },
      ],
      temperature: body.temperature,
      maxTokens: body.maxTokens,
    };

    const result = await pm.run(testRequest);
    return createJsonResponse(
      {
        success: result.success,
        response: result.data?.response,
        model: result.model,
        provider: result.provider,
        error: result.error,
      },
      result.success ? 200 : 502
    );
  },
  [requireAuth]
);

router.post(
  "/agent/embedding",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    const body = (await request.json()) as {
      text: string;
      provider?: ProviderName;
    };
    const pm = getProviderManager(env);
    const result = await pm.runEmbedding(body.text, body.provider);
    return createJsonResponse(
      {
        success: result.success,
        embedding: result.data?.response,
        model: result.model,
        error: result.error,
      },
      result.success ? 200 : 502
    );
  },
  [requireAuth]
);

// Root endpoint
router.get("/", async () => {
  return new Response("Agent Worker is running");
});

router.get(
  "/health",
  async (request: Request, env: Env, ctx: ExecutionContext) => {
    return healthCheck({ worker: "agent-worker" });
  }
);

const cronHandler = createCronHandler<Env>({
  name: "agent-worker",
  logger,
  handler: async (_event: ScheduledEvent, env: Env, ctx: ExecutionContext) => {
    ctx.waitUntil(runHousekeeping(env, logger));
    ctx.waitUntil(
      processRoutine(env, logger, {
        getProviderManager,
        getActiveTrailingStops,
      })
    );
  },
});

export default {
  fetch: withRequestLog<Env>(
    async (request: Request, env: Env, ctx: ExecutionContext) => {
      const cors = corsHeaders();
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: cors });
      }
      const response = await router.handle(request, env, ctx);
      const newResponse = new Response(response.body, response);
      for (const [key, value] of Object.entries(cors)) {
        newResponse.headers.set(key, value);
      }
      return newResponse;
    },
    { service: "agent-worker", module: "router" }
  ),

  async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext) {
    return await cronHandler(event, env, ctx);
  },

  // Export for testing
  processRoutine: (env: Env) =>
    processRoutine(env, logger, {
      getProviderManager,
      getActiveTrailingStops,
    }),
};

async function getActiveTrailingStops(env: Env): Promise<string[]> {
  try {
    const stopsList = await env.CONFIG_KV.list({ prefix: "trade:watermark:" });
    return stopsList.keys.map((k) => k.name);
  } catch (error: unknown) {
    logger.warn("Failed to list active trailing stops from KV", {
      error: toError(error),
    });
    return [];
  }
}
